### ISSUE TITLE
Никак не получается, чтобы дефолтное фото проставлялось

### ISSUE THREAD

**Issue by bsakhanov** [Joomla-Ukraine/JUImage#2]
Добрый день, Денис! 
в созданном файле "/html/layouts/joomla/content/intro_image1.php" в своем шаблоне
использую вашу библиотеку.

`<?php
JLoader::register('JUImage',  JPATH_LIBRARIES . '/juimage/JUImage.php');

$juImg = new JUImage();	
?>
<?php

$thumb = $juImg->render($images->image_intro, [
	'w'     	=> '300',
	'h'     	=> '200',
	'q'         => '65',
	'zc'        => 'C',
	'far'        => 'C',	
	'webp'      => true,
	'webp_q'    => '60',
	'webp_maxq' => '65',
	'cache'     => 'img'
	
]);
?>`

Все супер, превью картинки формируются, отличная библиотека! Вот только никак не получается, чтобы дефолтное фото проставлялось (на случай, если фото автор забыл проставить в статью). Пробовал использовать  указанный в редми пример с img_blank, но почему-то $config никак не хочет он работать! Что не так делаю?

**Comment by denysdesign** [comment]
Подфиксил. Сделал правки в README.md.

Сделать можно 2мя способами.

**Локальный**
```
JLoader::register('JUImage', JPATH_LIBRARIES . '/juimage/JUImage.php');

$JUImg  = new JUImage();

$avatar = $JUImg->render($row->filename, [
	'w'           => 75,
	'h'           => 75,
	'error_image' => 'image/error.png',
	'zc'          => 'T',
	'fltr_1'      => 'usm|70|0.3|2',
	'cache'       => 'img'
]);
```
**Глобально**
```
JLoader::register('JUImage', JPATH_LIBRARIES . '/juimage/JUImage.php');

$JUImg  = new JUImage([ 'img_blank' => 'image/error.png' ]);

$avatar = $JUImg->render($row->filename, [
	'w'           => 75,
	'h'           => 75,
	'zc'          => 'T',
	'fltr_1'      => 'usm|70|0.3|2',
	'cache'       => 'img'
]);
```

**Comment by bsakhanov** [comment]
что-то не получилось... Пусто, не вставляется дефолтное фото...
