### ISSUE TITLE
Ошибка при webp

### ISSUE THREAD

**Issue by ghost** [Joomla-Ukraine/JUImage#4]
Добрый день, уважаемые разработчики!
В Joomla 3 всё работает отлично до тех пор, пока не включаю поддержку webp:
$thumb = $juImg->render($item->imageSrc, [
					'w' => '614',
					'h' => '410',
					'q' => '60',
					'webp'      => true,
					'cache' => 'img'
				]); ?>

Как только я это включаю, сайт рушится и выдается сообщение: Object of class stdClass could not be converted to string
В чем может быть проблема?

**Comment by denysdesign** [comment]
Поддержка webp осуществляется через библиотеку GD2 или ImageMagick?

**Comment by ghost** [comment]
К сожалению я не знаю. А как это узнать? 
В материалах я использую изображения в формате webp через тег `<picture>`.
Значит что-то еще нужно? Нужно что-то где-то включить или плагин какой-то устанавливать?

Я посмотрел в настройках Joomla - "Информация о PHP", нашел вот что:

=============
	imagick
	=============
	imagick module: enabled
	imagick module version: @PACKAGE_VERSION@
	imagick classes: Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
	Imagick compiled with ImageMagick version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
	Imagick using ImageMagick library version: ImageMagick 6.9.10-68 Q16 x86_64 2021-02-24 https://imagemagick.org
	ImageMagick copyright: © 1999-2019 ImageMagick Studio LLC
	ImageMagick release date: 2021-02-24
	ImageMagick number of supported formats:: 236
	ImageMagick supported formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV

		=============
		imagick.locale_fix
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.progress_monitor
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.set_single_thread
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.shutdown_sleep_count
		=============
		Local Value: 10
		Master Value: 10

		=============
		imagick.skip_version_check
		=============
		Local Value: 0
		Master Value: 0

И вот еще:

=============
	gd
	=============
	GD Support: enabled
	GD Version: bundled (2.1.0 compatible)
	FreeType Support: enabled
	FreeType Linkage: with freetype
	FreeType Version: 2.8.0
	GIF Read Support: enabled
	GIF Create Support: enabled
	JPEG Support: enabled
	libJPEG Version: 6b
	PNG Support: enabled
	libPNG Version: 1.5.13
	WBMP Support: enabled
	XBM Support: enabled
	WebP Support: enabled
	BMP Support: enabled
	TGA Read Support: enabled

**Comment by denysdesign** [comment]
Обновите пакет и попробуйте отключить для webp обработку устаревшей версией Imagemagick:

```php
<?php

$thumb = $juImg->render('images/sampledata/fruitshop/apple.jpg', [
	'w'           => '300',
	'h'           => '100',
	'q'           => '95',
	'webp'        => true,
	'imagemagick' => false
]);
?>
```

**Comment by ghost** [comment]
Супер! Всё получилось! Огромное СПАСИБО! 
JUImage - просто КЛАСС!

**Comment by denysdesign** [comment]
Где используете библиотеку?

**Comment by ghost** [comment]
Joomla 3.9.25, PHP 8.0
Я использую в стандартном модуле "Материалы-Новости" (mod_articles_news). 
Теперь, когда всё работает прекрасно, еще хочу переделать "Блог категории".

**Comment by denysdesign** [comment]
Можно включить системный плагин и не инклюдить каждый раз библиотеку

**Comment by ghost** [comment]
У меня System - JUImage включен.

А в шаблоне (mod_articles_news)  в файле default.php я вставляю:
`JLoader::register('JUImage',  JPATH_LIBRARIES . '/juimage/JUImage.php');`

А в файле _item.php уже вывожу картинки так:
```
<?php $juImg = new JUImage();

	$thumb = $juImg->render($item->imageSrc, [
		'w' => '614',
		'h' => '410',
		'q' => '60',
		'webp' => true,
		'imagemagick' => false,
		'cache' => 'img'
	]); ?>

<picture>
	<source srcset="<?php echo $thumb->webp; ?>" type="image/webp">
	<img src="<?php echo $thumb->img; ?>" alt="<?php echo $item->imageCaption; ?>">
</picture>
```
