### ISSUE TITLE
JUImage vs Joomla4

### ISSUE THREAD

**Issue by ghost** [Joomla-Ukraine/JUImage#8]
Добрый день уважаемые разработчики!
Подскажите пожалуйста как решить проблему. Я использую JUImage для вывода новостей, картинка берётся из изображения вводного текста. В шаблоне это выглядит так:

```
<?php if ($params->get('img_intro_full') !== 'none' && !empty($item->imageSrc)) : ?>
	<a class="latest-article__img" href="<?php echo $item->link; ?>">
		<?php $juImg = new JUImage();

		$thumb = $juImg->render($item->imageSrc, [
			'w'     => '576',
			'h'     => '384',
			'q'     => '60',
			'webp' => true,
			'imagemagick' => false,
			'cache' => 'img'
		]); ?>

	<picture>
		<source srcset="<?php echo $thumb->webp; ?>" type="image/webp">
		<img src="<?php echo $thumb->img; ?>" alt="<?php echo $item->imageCaption; ?>">
	</picture>

	<?php if (!empty($item->imageCaption)) : ?>
		<span class="img-caption">
			<?php echo $item->imageCaption; ?>
		</span>
	<?php endif; ?>
	</a>
<?php endif; ?>
```

До обновления на Joomla 4 всё работало прекрасно, на Joomla 3 нет никаких проблем.
Но после обновления превьюшки не генерируются. Точнее, вместо превью выводится стандартная картинка "NO IMAGE". Я так подозреваю, что это связано с ссылками на вступительное изображение в Joomla 4.

Раньше (на Joomla 3) ссылка на вступительное изображение была обычная:
`<img src="/images/image.jpg">`

А вот как Joomla 4 генерирует ссылку на вступительное изображение:
`<img src="/images/image.jpg#joomlaImage://local-images/image.jpg?width=576&amp;height=384">`

Может как-то регулярку задействовать чтобы лишнее отрезать? Типа того `/#joomlaImage:\/\/?([^\'" >]+)/gmi`

**Comment by bsakhanov** [comment]
Подтверждаю. Что-то не работает на  Joomla 4

**Comment by ghost** [comment]
> Подтверждаю. Что-то не работает на Joomla 4

Я добавил регулярку и всё работает. 
```
<?php
$regexImageSrc = '/#joomlaImage?([^\'" >]+)/';
?>
<?php $juImg = new JUImage();
	$thumb = $juImg->render(preg_replace($regexImageSrc, '', $item->imageSrc), [
		'w' => '576',
		'h' => '384',
		'q' => '60',
		'webp' => true,
		'imagemagick' => false,
		'cache' => 'img'
]); ?>
```

**Comment by bsakhanov** [comment]
Спасибо! Да, с вашей поправкой (с включением регулярки) всё заработало!

Но думается, этот вариант использования нужно включить в файл Redmi в качестве примера для использования библиотеки JUImage на четвертой версии Joomla. Потому что при редакторе TinyMCE, проставленном в качестве дефолтного, как раз и выходит эта ошибка, поскольку для вступительного (image_intro) и полного изображения (image_fulltext) генерируются ссылки с указанием атрибутов, чего в Joomla 3 не было. 

Иными словами, Joomla 4 требует дополнительного очищения получаемой ссылки для изображения, и только после этого становится возможным применение скриптов самой библиотеки JUImage для необходимой обработки картинок.
