### ISSUE TITLE
Feature request: AVIF support

### ISSUE THREAD

**Issue by JoomBall** [Joomla-Ukraine/JUImage#9]
AVIF image format support has landed in PHP 8.1, brings drastic file size reductions and is supported by more and more browsers.
Would be great if AVIF would be supported by JUImage in nearer future :-) . Are there plans to include AVIF support?

Thank you very much for this wonderful library.

**Comment by denysdesign** [comment]
Please update https://github.com/Joomla-Ukraine/JUImage/releases/tag/5.5

**Comment by JoomBall** [comment]
Thank you very much @denysdesign , it works well but if you want and you can add 2 improvements it would be great.

1) The first is that the avif image should be smaller than webp. In my code I transformed webp to avif and improved image size.

imageavif(imagecreatefromwebp($thumb->webp), $image->avif);

2) Second if it is possible to return the 2 types of image at the same time.

`$attr = array('w'   => $params->get('img_width'),
						'h'     	=> $params->get('img_height'),
						'q'         => $params->get('img_quality', 75),
						'avif'      => true,
						'webp'      => true,
						'webp_q'    => '80',
						'webp_maxq' => '85',
						'cache' => 'cache/images'
				);`

Now returns:

stdClass Object
(
    [img] => cache/images/x/d/image0-411791aa.jpg
    [webp] => cache/images/x/d/image0-cd5b1a06.webp
)


Thanks a lot!

**Comment by denysdesign** [comment]
If you want to compress any formats, use any combine constructions with format option (f).

Please see for combine webp and avif formats here https://github.com/Joomla-Ukraine/JUImage#how-to-combine-webp-and-avif
